# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0002_auto_20180609_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='ambulatory',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
