# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0003_ride_ambulatory'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='dropoff_room',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='pickup_room',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
