# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0004_auto_20180610_0026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='appointment_date',
            new_name='pickup_date',
        ),
        migrations.RenameField(
            model_name='ride',
            old_name='appointment_time',
            new_name='pickup_time',
        ),
    ]
