# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-10 00:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0005_auto_20180610_0029'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='client_number',
            new_name='accompany_number',
        ),
    ]
