# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0008_auto_20180610_0034'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='appointment_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ride',
            name='pickup_datetime',
            field=models.DateField(),
        ),
    ]
