# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0009_auto_20180620_0121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='approved',
            field=models.BooleanField(),
        ),
    ]
