# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0010_auto_20180701_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='duration',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
