# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-01 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0011_auto_20180701_1608'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='doctor_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='doctor_office_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='doctor_suite_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
