# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0012_auto_20180701_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='approved',
            field=models.NullBooleanField(),
        ),
    ]
