# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 00:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0013_auto_20180702_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pickup_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
