# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-02 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0014_ride_pickup_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='primary_facility_address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='primary_facility_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='primary_facility_number',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
