# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0018_auto_20180702_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='pickup_time',
            field=models.TimeField(null=True),
        ),
    ]
