# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-07 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0019_auto_20180705_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='friday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='monday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='repeat_ride',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='saturday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='sunday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='thursday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='tuesday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ride',
            name='wednesday',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
