# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-08 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0021_auto_20180707_0459'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastRide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pickup_address', models.CharField(max_length=255)),
                ('dropoff_address', models.CharField(max_length=255)),
                ('pickup_room', models.IntegerField()),
                ('dropoff_room', models.IntegerField()),
                ('pickup_datetime', models.DateField()),
                ('pickup_time', models.TimeField(null=True)),
                ('appointment_time', models.TimeField()),
                ('duration', models.CharField(max_length=255)),
                ('round_trip', models.BooleanField()),
                ('ambulatory', models.BooleanField()),
                ('doctor_name', models.CharField(max_length=255)),
                ('doctor_suite_number', models.CharField(max_length=255)),
                ('doctor_office_number', models.CharField(max_length=255)),
                ('comments', models.TextField()),
                ('facility_number', models.CharField(max_length=255)),
                ('accompany_number', models.CharField(max_length=255)),
                ('accompany_name', models.CharField(max_length=255)),
                ('approved', models.NullBooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repeat_ride', models.BooleanField()),
                ('monday', models.BooleanField()),
                ('tuesday', models.BooleanField()),
                ('wednesday', models.BooleanField()),
                ('thursday', models.BooleanField()),
                ('friday', models.BooleanField()),
                ('saturday', models.BooleanField()),
                ('sunday', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_rides', to='prettyboyapp.User')),
            ],
        ),
    ]
