# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0022_pastride'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
