# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-09 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0023_ride_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastride',
            name='dropoff_number',
            field=models.CharField(default=2318814890, max_length=255),
            preserve_default=False,
        ),
    ]
