# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prettyboyapp', '0027_auto_20180812_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='pastride',
            name='additional_destination_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pastride',
            name='additional_destination_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pastride',
            name='additional_time_1',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastride',
            name='additional_time_2',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pastride',
            name='facility_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastride',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pastride',
            name='private_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='facility_pay',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ride',
            name='private_pay',
            field=models.BooleanField(default=False),
        ),
    ]
